set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_CXX_COMPILER_TARGET x86_64-apple-darwin18)
# set(CMAKE_SYSROOT /clang)

set(CMAKE_CXX_COMPILER /clang/bin/clang++)
set(CMAKE_C_COMPILER /clang/bin/clang)

set(CMAKE_CXX_FLAGS "-v -stdlib=libc++" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "-v" CACHE STRING "" FORCE)
# set(CMAKE_EXE_LINKER_FLAGS "-v -fuse-ld=lld" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
